image: maven:3.5-jdk-8-alpine

cache:
  key: "$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
  paths:
    - .m2/

before_script:
  - mkdir -p $HOME/.m2/
  - echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                          https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <localRepository>'$PWD'/.m2</localRepository>
            <profiles>
              <profile>
                <repositories>
                  <repository>
                    <snapshots>
                      <enabled>false</enabled>
                    </snapshots>
                    <id>central</id>
                    <name>libs-release</name>
                    <url>http://artifacts.lockss.org:8081/artifactory/libs-release</url>
                  </repository>
                  <repository>
                    <snapshots />
                    <id>snapshots</id>
                    <name>libs-snapshot</name>
                    <url>http://artifacts.lockss.org:8081/artifactory/libs-snapshot</url>
                  </repository>
                </repositories>
                <pluginRepositories>
                  <pluginRepository>
                    <snapshots>
                      <enabled>false</enabled>
                    </snapshots>
                    <id>central</id>
                    <name>libs-release</name>
                    <url>http://artifacts.lockss.org:8081/artifactory/libs-release</url>
                  </pluginRepository>
                  <pluginRepository>
                    <snapshots />
                    <id>snapshots</id>
                    <name>libs-snapshot</name>
                    <url>http://artifacts.lockss.org:8081/artifactory/libs-snapshot</url>
                  </pluginRepository>
                </pluginRepositories>
                <id>artifactory</id>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>artifactory</activeProfile>
            </activeProfiles>
            <mirrors>
              <mirror>
                <mirrorOf>*</mirrorOf>
                <name>libs-snapshot</name>
                <url>http://artifacts.lockss.org:8081/artifactory/libs-snapshot</url>
                <id>libs-snapshot</id>
              </mirror>
            </mirrors>
          </settings>' > $HOME/.m2/settings.xml

job1:
    stage: build
    script: "mvn package -B"
    only:
    - master
    tags:
    - docker
    - maven