#!/bin/bash

# make sure we have an update lockss-daemon git branch
echo "Initializing lockss-daemon submodule...\n"
git submodule init
git submodule update
cd lockss-daemon
git checkout snafl-changes
echo "Building LOCKSS jars...\n"
ant jar-lockss
ant jar-plugins
cd ..
# make sure we install the missing mvn jars
# the lockss libs we use
echo "Installing LOCKSS jars to maven repo...\n"
mvn install:install-file -Dfile=lockss-daemon/lib/lockss.jar -DpomFile=poms/lockss-2016.pom 
mvn install:install-file -Dfile=lockss-daemon/lib/lockss-plugins.jar -DpomFile=poms/lockss-plugins-2016.pom
echo "Installing old or patched jars to maven repo...\n"
# - this is the pre-apache verision of the derby jars
mvn install:install-file -Dfile=lockss-daemon/lib/derby.jar -DpomFile=poms/derby-9.1.pom
mvn install:install-file -Dfile=lockss-daemon/lib/derbyclient.jar -DpomFile=poms/derbyclient-9.1.pom
mvn install:install-file -Dfile=lockss-daemon/lib/derbynet.jar -DpomFile=poms/derbynet-9.1.pom
# these are patched versions of older libs
mvn install:install-file -Dfile=lockss-daemon/lib/heritrix-commons-3.1.0-p1.jar -DpomFile=poms/heritrix-commons-3.1.0-p1.pom
mvn install:install-file -Dfile=lockss-daemon/lib/htmlparser-1.6p.jar -DpomFile=poms/htmlparser-1.6p.pom
mvn install:install-file -Dfile=lockss-daemon/lib/jetty-5.1.5L.jar -DpomFile=poms/jetty-5.1.5L.pom
mvn install:install-file -Dfile=lockss-daemon/lib/JimiProClasses.jar -DpomFile=poms/JimiProClasses.pom
mvn install:install-file -Dfile=lockss-daemon/lib/JoSQL-2.2.jar -DpomFile=poms/JoSQL-2.2.pom
mvn install:install-file -Dfile=lockss-daemon/lib/oiosaml.java-21188-PATCHED.jar -DpomFile=poms/oiosaml.java-21188-PATCHED.pom
mvn install:install-file -Dfile=lockss-daemon/lib/PDFBox-0.7.3.jar -DpomFile=poms/PDFBox-0.7.3.pom
mvn install:install-file -Dfile=lockss-daemon/lib/rdf-api-2001-01-19.jar -DpomFile=poms/rdf-api-2001-01-19.pom

# run maven build and test
echo "Running build and tests..."
mvn clean package
echo "Initialization is now complete!"